# Generated by Django 6.0.3 on 2026-03-30 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traiteurs', '0002_alter_traiteur_est_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='traiteur',
            name='experience',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traiteur',
            name='note',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='traiteur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='traiteur',
            name='specialites',
        ),
        migrations.AddField(
            model_name='traiteur',
            name='specialites',
            field=models.ManyToManyField(to='traiteurs.specialite'),
        ),
    ]
